microsoft/navcontainerhelper

- NavContainerHelper.psm1
With this change you don't need to type the container name, but can tab through the available containers, same es explained [here](https://www.axians-infoma.de/navblog/easily-enter-a-container-through-powersshell/) in the Update section. The result looks similar to [this](https://www.axians-infoma.de/wp-content/uploads/2017/08/enter-container.gif)
> add dynamic container name resolution

- NavContainerHelper.psm1
Use new -exportObjectsToText switch.
> Ability to create CSide environment but not have to export objects

- ContainerInfo/Get-NavContainerDebugInfo.ps1
- NavContainerHelper.psm1
I think it could be useful to have a function that will return all necessary information to be able to "*debug*" issues.
This is just a draft, more information could be included in the future (networking etc.) if necessary.
> Add function to retrieve debug information

- NavContainerHelper.md
I see myself using this a lot as reference for my own scripts, so having a TOC instead of doing search and find would help a lot
> Create a table of content with links

- AppHandling/Compile-AppInNavContainer.ps1
This should solve #182 
Test Symbols will be added as dependency if "test" node ~~exists~~ is not empty in app.json
> Add test symbols as dependency

- AppHandling/Sync-NavContainerApp.ps1
I've added the paramter "Mode" that gets passed along to the underlying Sync-NAVApp cmdlet. Default is "Add", just as stated in MS documentation.
> Added support for "Mode" in Sync-NavContainerApp

- Misc/Convert-ALCOutputToAzureDevOps.ps1
- NavContainerHelper.psd1
- NavContainerHelper.psm1
to format used by Azure DevOps Pipelines.
Based on my code from https://dynamicsuser.net/nav/b/kine/posts/alc-exe-output-formatting-for-tfs-vsts
> Added Convert-ALCOutputToAzureDevOps to covert ALC.EXE output

- AppHandling/Compile-AppInNavContainer.ps1
I am offering solution for #207 - not tested...
> Fix: Compile app existing app check fix #207

- AppHandling/Compile-AppInNavContainer.ps1
- ObjectHandling/Invoke-NavContainerCodeunit.ps1
Added check, if property "dependencies" exists in appJsonObject to prevent error if no dependencies are included in app.json.
> Added Check if app.json includes dependencies

- AppHandling/Compile-AppInNavContainer.ps1
- AppHandling/Convert-ALCOutputToAzureDevOps.ps1
Compile-AppInNavContainer can now run the StyleCop check with the parameter EnableCodeCop.
With the new parameter FailOn, it is now possible to let fail the build pipeline in AzureDevOps (based on warnings and/or errors occurred during the compile).
- none (default) - same as before, only output of the errors and warnings
- warning - fail build if a warning or error occurred
- error - fail build if a error occurred
> Added support for StyleCop and improved Convert-ALCOutputToAzureDevOps

- AppHandling/Publish-NavContainerApp.ps1
Fix for error introduced by PR #280
> Fixed "Cannot bind parameter 'Mode'" error

- ContainerHandling/New-NavContainer.ps1
Fix for https://github.com/Microsoft/navcontainerhelper/issues/374
> Check, the apps before unpublish

- ContainerHandling/New-NavContainer.ps1
minor bug: client version was used instead of server version
> fix used version

- SymbolHandling/Generate-SymbolsInNavContainer.ps1
#528 ... fix the error message from call
> error message fixed

- AppHandling/Create-AlProjectFolderFromNavContainer.ps1
- AppHandling/Publish-NewApplicationToNavContainer.ps1
- ContainerHandling/New-NavContainer.ps1
Create-AlProjectfolderFromNavContainer
- new parameter **useBaseAppProperties** added
- if set properties for app.json are retrieved from base app actually installed inside container
Publish-NewApplicationToNavContainer
- new parameter **saveData** added
- if set database is cleaned without deleting data of installed apps
New-NavContainer:
- Translations folder added when extracting files from base app in order to keep localization when building new base app
> Enhancements for AL app handling

- ContainerHandling/Setup-TraefikContainerForNavContainers.ps1
> Change Examples for Setup-TraefikContainerForNavContainers.ps1

- AppHandling/Extract-AppFileToFolder.ps1
- ContainerHandling/New-NavContainer.ps1
- ContainerHandling/Remove-NavContainer.ps1
- ContainerHandling/updatehosts.ps1
- ReleaseNotes.txt
Add host.containerhelper.internal to container hosts file for container to be able to connect to services at the host
Add parameter GenerateAppJson to Extract-AppFileToFolder in order to generate a sample app.json based on the app manifest
Add parameter VsixFile to New-BCContainer in order to override the .vsix file in the image at runtime
> App Validation fixes

- ContainerHandling/New-NavContainer.ps1
Pull Request inserts a missing escape character.
> escape $ with `

- AppHandling/Sort-AppFoldersByDependencies.ps1
In addition to PR #855 - fixed array of names of the unkown app dependencies in Sort-AppFoldersByDependencies.ps1
> fixed array of unknown app dependencies

- ContainerHandling/New-NavContainer.ps1
If Docker is not running, you will get the error message that you should switch to Windows containers:
After this pull request, the error message that Docker is not running is displayed:
> First check "Docker is running" before checking "Windows Container"

- AppHandling/PsTestFunctions.ps1
> Fix time format in XUnit test result file

- Misc/Get-BCArtifactUrl.ps1
As promised - based on the API.
I didn't look into the bcinsider-part (yet).
> Get-BCArtifactUrl

- Misc/Remove-DesktopShortcut.ps1
fixes #1105
#1102 could not reproduced with or without this fix
> fixed variable reuse at shortcut deletion

- ContainerHandling/Get-BestGenericImageName.ps1
- CreateScript.ps1
- ReleaseNotes.txt
Issue #1107 Add hostOsVersion parameter to Get-BestGenericImageName
+Back on ConnectionString or bakfile question doesn't work in New-BcContainerWizard
> Issue #1107

- ObjectHandling/Import-TestToolkitToNavContainer.ps1
- ReleaseNotes.txt
> Issue #1220

- AppHandling/UnPublish-NavContainerApp.ps1
We need to add the -tenant parameter if we have a multitenant container running and the app has been installed into the tenant scope.
> Add multitenant support for unpublish

- AppHandling/Compile-AppInNavContainer.ps1
Wait for .app file to become available.
> Issue #1299

- AppHandling/Run-AlPipeline.ps1
- ReleaseNotes.txt
Add parameter description to Run-AlPipeline
Set JUnit as default output from Run-AlPipeline
> runpipeline fixes

- NavContainerHelper.md
Tested them all.
PS: The CLA-bot isn't working in this repo, is it?
> Fixed broken links in NavContainerHelper.md

- BcContainerHelper.psm1
Not sure how you define that list, but we have a "translation" in place for ro -> w1 as well and could get rid of it if it is ok for you to add here as well
> add Romania

- AppHandling/Compile-AppInNavContainer.ps1
- AppHandling/Publish-BuildOutputToStorage.ps1
- AppHandling/Publish-PerTenantExtensionApps.ps1
- AppHandling/Run-AlCops.ps1
- AppHandling/Run-AlPipeline.ps1
- AppHandling/Run-AlValidation.ps1
- AppHandling/Sort-AppFilesByDependencies.ps1
- HelperFunctions.ps1
- ObjectHandling/Convert-Txt2Al.ps1
- ReleaseNotes.txt
- UserHandling/Setup-NavContainerTestUsers.ps1
PowerShell sometimes uses 8-3 notation for $env:temp
> Issue #1552

- AppHandling/Compile-AppInNavContainer.ps1
- AppHandling/Run-AlCops.ps1
- AppHandling/Run-AlValidation.ps1
- ReleaseNotes.txt
Add parameter CopySymbolsFromContainer to Compile-AppInBcContainer to speed up symbols download
Use CopySymbolsFromContainer in Run-AlCops
> Copy Symbols From Container

- AppHandling/Sign-NavContainerApp.ps1
- ReleaseNotes.txt
> Issue #1566

- AppHandling/Extract-AppFileToFolder.ps1
- AppHandling/Run-AlValidation.ps1
- ReleaseNotes.txt
Run-AlValidation and Extract-AppFileToFolder require absolute paths
> Issue #1577

- BcContainerHelper.psd1
- BcContainerHelper.psm1
- BcSaaS/Get-BcEnvironments.ps1
- BcSaaS/Get-BcPublishedApps.ps1
- BcSaaS/New-BcEnvironment.ps1
- BcSaaS/Remove-BcEnvironment.ps1
- BcSaaS/Set-BcEnvironmentApplicationInsightsKey.ps1
- HelperFunctions.ps1
- ReleaseNotes.txt
Add functions New-BcEnvironment, Remove-BcEnvironment and Set-BcEnvironmentApplicationInsightsKey
> add functions

- AppHandling/Extract-AppFileToFolder.ps1
- ReleaseNotes.txt
Run-AlValidation with "preprocessorSymbols"
> Issue #1704

- PackageHandling/Resolve-DependenciesFromAzureFeed.ps1
- Tests/PackageHandling.ps1
In strict mode things work a bit diffrent. Specially with catches an $_ one needs to take care. 
Added an strict mode save check for properties in the app.json. 
Added an id variable so that the id could be printed without an error in the catch phrase. 
sorry for the trouble...
> Strict mode got me bad

- AzureAD/Create-AadAppsForNav.ps1
> Add support for Service principal in Create-AadAppsForNav

- BcContainerHelper.psm1
- ContainerHandling/Get-NavContainerSession.ps1
- ReleaseNotes.txt
Issue #1803 Set PSSession Timeout to 0 (no timeout) overridable in config
> Issue #1803

- Bacpac/Restore-BcDatabaseFromArtifacts.ps1
> Using SqlServer PS module to load the Smo libraries

- ContainerHandling/New-NavContainer.ps1
- ContainerHandling/New-NavImage.ps1
- Misc/Add-FontsToNavContainer.ps1
- ReleaseNotes.txt
Fixes #1812
Is the line ending normalization in ContainerHandling/New-NavImage.ps1 okay?
> Allow arrays as path parameter for font-related functions

- AppHandling/ClientContext.ps1
> #1917: If the client context throws an error, re-throw it as exception

- AppHandling/Run-AlPipeline.ps1
- ReleaseNotes.txt
> Appinsightsconnection

- PackageHandling/Resolve-DependenciesFromAzureFeed.ps1
There is a bug which doesn't allow you to have an test app with a dependency to the main app in the same folder (which it should).
In that case app will be resolved from feed as a dependency from test and installed. 
This will cause the build of app to fail, since it's already present in another version. 
I fixed this issue by including an option to ignore dependencies and always add the first lvl app ids to it. 
Besides fixing the issue this gives you the power, to for example ignore microsoft apps or anything that should not be resolved from feed.
> Fixing bug that downloaded all apps from first lvl

- ContainerHandling/New-NavContainer.ps1
Wanted to know how 'copyTables' works and what it does. Stumbled across the 'if'
> Small correction

- AppHandling/Clean-BcContainerDatabase.ps1
- AppHandling/Publish-NewApplicationToNavContainer.ps1
Sorry, there were two more. :) Did not see them at first.
> Further correction of 'if'

- AppHandling/Publish-NavContainerApp.ps1
Changed as already discussed in #2093
> Allow upgrade when old app version is already uninstalled

- ContainerHandling/New-NavContainer.ps1
> Look for a running "dockerd" process and not a running "docker" service to determine if docker is running

- BcSaaS/New-BcAuthContext.ps1
- ReleaseNotes.txt
Publish-BcContainerApp as Delegated Admin
> Issue #2267

- AppHandling/ClientContext.ps1
- ContainerHandling/New-NavImage.ps1
Incompatible with netstandard version of Client DLL
> Remove OpenFormWithFilter from ClientContext

- AppHandling/Get-NavContainerAppRuntimePackage.ps1
Add new parameter IncludeSourceInPackageFile to take advantage of the new resource policy setting.
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-creating-runtime-packages
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-security-settings-and-ip-protection
> New parameter IncludeSourceInPackageFile

- AppHandling/Compile-AppInNavContainer.ps1
- BcContainerHelper.psm1
- ContainerHandling/Invoke-ScriptInNavContainer.ps1
- ContainerHandling/Remove-NavContainerSession.ps1
- ReleaseNotes.txt
Improve Out of memory detection when running using docker exec (without pssession)
Improve Invoke-ScriptInBcContainer when running using docker exec (without pssession)
- Add try/catch inside script block to catch error better
Avoid Pssession in Azure DevOps and GitHub Actions
Add kill switch for pssessions
> Improvements

- BcContainerHelper.psd1
@freddydk  Removed incorrect comma from function export list, otherwise module import is not possible.
> Fix: Removed incorrect comma from function export list

- BcContainerHelper.psd1
- BcContainerHelper.psm1
- BcSaaS/Get-BcScheduledUpgrade.ps1
- BcSaaS/Reschedule-BcUpgrade.ps1
- ReleaseNotes.txt
Hi Freddy,
we would love to integrate more BC Admin Center API Requests into BCContainerHelper.
In this PR i start with Environment Upgrade Handling. You can check if a upgrade for an environment is scheduled by running Get-BcScheduledUpgrade and reschedule upgrades by running Reschedule-BcUpgrade.
The Functions use this API: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/administration-center-api_reschedule_updates
I tried to copy the style of your other bcsaas functions :) 
Feedback is welcome!
> BCSaaS Environment Upgrade Handling

- PackageHandling/Install-AzDevops.ps1
> Changed upgrade process.

- AppHandling/Compile-AppInNavContainer.ps1
- AppHandling/Convert-ALCOutputToAzureDevOps.ps1
- AppHandling/Run-AlPipeline.ps1
https://github.com/microsoft/AL-Go/issues/225
https://github.com/microsoft/AL-Go/issues/220
> Two AL-Go bugs

- .github/workflows/CI.yaml
- .github/workflows/PullRequestHandler.yaml
- AppHandling/PsTestFunctions.ps1
- AppHandling/Run-AlPipeline.ps1
- AppHandling/Run-TestsInNavContainer.ps1
- BcContainerHelper.psm1
Add RenewClientContextBetweenTests settings
Add functionality to get Container Event Log file when failed builds
> fix system test runs

- .github/workflows/CI.yaml
- ContainerHandling/Wait-NavContainerReady.ps1
- ContainerInfo/Get-NavContainerSharedFolders.ps1
- ReleaseNotes.txt
> Issue #2798

- .github/workflows/CI.yaml
- Tests/GetAndRunTests (Windows Auth).Tests.ps1
- Tests/GetAndRunTests (Windows Auth).ps1
- Tests/GetAndRunTests (version 21).Tests.ps1
- Tests/Run-AlPipeline (Windows Auth).Tests.ps1
+ add tests for Run-AlPipeline + GetAndRunTests using Windows authentication
+ add tests for BC 21
> Run Tests on PS7

- AppHandling/Sort-AppFilesByDependencies.ps1
- Common/Invoke-gh.ps1
- Common/Invoke-git.ps1
- HelperFunctions.ps1
- NuGet/Publish-BcNuGetPackageToContainer.ps1
+ support for input pipe for invoke-gh and invoke-git
> Issue #2813

- ContainerHandling/traefik/CheckHealth_https.ps1
> Issue #2842

- Artifacts/Download-Artifacts.ps1
- ReleaseNotes.txt
> Fix Missing cu version in nav2018 Artifact Manifest

- AppHandling/Publish-NavContainerApp.ps1
- ReleaseNotes.txt
Publish to Dev Scope with upgrade causes dependency issues
> Issue #2858

- AppHandling/Install-NAVSipCryptoProviderFromNavContainer.ps1
- ReleaseNotes.txt
> Issue NavSip.dll missing since Tuesday

- AppHandling/Run-AlPipeline.ps1
- AppHandling/Sort-AppFilesByDependencies.ps1
- TelemetryHelper.ps1
> PowerShell 7 and Linux fixes

- ContainerInfo/Get-NavContainerIpAddress.ps1
- ReleaseNotes.txt
Regression in Get-ContainerIpAddress
> Issue #2970

- Saas/Get-BcEnvironments.ps1
When trying to get the saas environment the scripts fail with wrong parameter;
> Corrected wrong parameter for create-saasurl;

- AppHandling/Sort-AppFilesByDependencies.ps1
- ReleaseNotes.txt
- Saas/Publish-PerTenantExtensionApps.ps1
Exclude Runtime Packages from Publish-PerTenantExtensionApps
> excluderuntimepackages

- AL-Go/New-ALGoAuthContext.ps1
- HelperFunctions.ps1
- ReleaseNotes.txt
Issue #3014 New-BcCompilerFolder requires 7zip
Add parameters for PowerPlatform Authentication to New-ALGoAuthContext (for use with upcoming feature to have PP in AL-Go)
> Issue #3014 + PP Auth

- PackageHandling/Install-AzDevops.ps1
> Fixed Azure CLI install 

- AppHandling/Compile-AppInNavContainer.ps1
- CompilerFolderHandling/Compile-AppWithBcCompilerFolder.ps1
- ReleaseNotes.txt
Support URLs in includeRuleSets
Feature: https://learn.microsoft.com/en-us/dynamics365/release-plan/2023wave1/smb/dynamics365-business-central/urls-includerulesets
> Add EnableExternalRulesets Support to compile functions

- AppHandling/Publish-NavContainerApp.ps1
- ContainerHandling/Flush-ContainerHelperCache.ps1
- ContainerHandling/Remove-NavContainerSession.ps1
- HelperFunctions.ps1
- ReleaseNotes.txt
Add new option (exitedContainers) on Flush-ContainerHelperCache. Note that exited containers are NOT remove by the all flag, you need all,exitedContainers
Add resilience to Remove-BcContainerSession
Issue #3116 Publish-NavContainerApp: Exception setting "ServerCertificateCustomValidationCallback": "Cannot convert the "static bool DisabledServerCertificateValidationCallback
> Issue #3116 + 2 enhancements

- AppHandling/Run-AlPipeline.ps1
- AppHandling/Run-AlValidation.ps1
- AzureVM/Replace-NavServerContainer.ps1
- ContainerHandling/Setup-TraefikContainerForNavContainers.ps1
- ReleaseNotes.txt
Fix issues with new Docker Desktop version on PowerShell 5
> Issue #3118

- CompilerFolderHandling/Compile-AppWithBcCompilerFolder.ps1
- CompilerFolderHandling/New-BcCompilerFolder.ps1
Even when Linux version of alc isn't included.
> Support building on Linux

- AppHandling/Run-AlPipeline.ps1
- AppSource/Invoke-IngestionAPI.ps1
- ReleaseNotes.txt
Get-AppSourceProduct returns 404 Not Found
> Issue #3151

- UserHandling/Setup-NavContainerTestUsers.ps1
Typo-Fix in Setup-NavContainerTestUsers.ps1
> Typo-Fix in Setup-NavContainerTestUsers.ps1

- AppHandling/Start-NavContainerAppDataUpgrade.ps1
- Common/ConvertTo-HashTable.ps1
- ReleaseNotes.txt
Provide same parameters from Start-NAVAppDataUpgrade to Start-BcContainerAppDataUpgrade.
> feat: Adds new parameters to Start-BcContainerAppDataUpgrade

- AppHandling/Publish-NavContainerApp.ps1
- ReleaseNotes.txt
Fix for issue #3146
Add -force on Install-NavApp (as it is already done on Publish-NavApp and Sync-NavApp)
> issue 3146

- AppHandling/Sign-NavContainerApp.ps1
- ReleaseNotes.txt
Download new NavSip prerequisites in version 23.0.12034.12480
> Issue #3190

- AppHandling/Run-AlPipeline.ps1
- ReleaseNotes.txt
Fix for issue https://github.com/microsoft/AL-Go/issues/709
> Include unknown app dependencies from previous apps (which doesn't already exist in unknown app dependencies)

- Common/Invoke-gh.ps1
- Common/Invoke-git.ps1
- HelperFunctions.ps1
- ReleaseNotes.txt
And do not hide real reason for the error
> Fix size problem in invoke-gh

- AppHandling/Run-AlValidation.ps1
- ReleaseNotes.txt
> Issue #3219

- AppHandling/Compile-AppInNavContainer.ps1
- AppHandling/Run-AlPipeline.ps1
- ReleaseNotes.txt
Do not attempt to download symbols if no URL is set.
Do not attempt to get app info from a filesonly container.
> Fix compile with filesonly

- Tests/AppHandling (NAV).Tests.ps1
- Tests/AppHandling.Tests.ps1
- Tests/_TestRunOne.ps1
Test failure - the NAV ALC compiler didn't support errorlog
> Move errorlog tests to BC apphandling

- AppHandling/Replace-DependenciesInAppFile.ps1
- ReleaseNotes.txt
> add parameter to replace versionnumber

- Artifacts/Get-BCArtifactUrl.ps1
- ReleaseNotes.txt
> Issue 3259

- Misc/Copy-ItemToBcContainer.ps1
> #3262: Fix "access denied" error when copying subfolders

- NuGet/Download-BcNuGetPackageToFolder.ps1
- NuGet/Find-BcNuGetPackage.ps1
- NuGet/NuGetFeedClass.ps1
> Use GitHub API when querying GitHub Packages

- Common/Download-File.ps1
- ContainerHandling/Get-LatestAlLanguageExtensionUrl.ps1
- HelperFunctions.ps1
- NuGet/Download-BcNuGetPackageToFolder.ps1
- NuGet/New-BcNuGetPackage.ps1
- NuGet/NuGetFeedClass.ps1
Support for runtime packages on NuGet
Bugfix when exactly one matching package on Azure DevOps
Example of runtime packages here https://dev.azure.com/freddydk/apps/_artifacts/feed/MyRuntimePackages
> support for runtime packages on NuGet

- AppHandling/Run-AlPipeline.ps1
Closes #3296
Adding an override to Compile-AppWithBcCompilerFolder. There is one for Compile-AppInBcContainer already, but I think this one should exist too.
> Closes #3296

- BC.HelperFunctions.ps1
- CompilerFolderHandling/Compile-AppWithBcCompilerFolder.ps1
- CompilerFolderHandling/New-BcCompilerFolder.ps1
Issue warning and errors if settings in the settings file doesn't exist or are of a wrong type
Change setting, which was of a wrong type
> Fixes #3302

- ReleaseNotes.txt
- Saas/Copy-BcEnvironment.ps1
- Saas/Get-BcEnvironmentAvailableRestorePeriods.ps1
- Saas/Get-BcEnvironmentOperations.ps1
- Saas/Get-BcEnvironmentUpdateWindow.ps1
- Saas/Get-BcEnvironmentUsedStorage.ps1
- Saas/Get-BcEnvironments.ps1
- Saas/New-BcEnvironment.ps1
- Saas/Remove-BcEnvironment.ps1
- Saas/Rename-BcEnvironment.ps1
- Saas/Restore-BcEnvironment.ps1
- Saas/Set-BcEnvironmentUpdateWindow.ps1
- Saas/Wait-BcEnvironmentReady.ps1
> use API v2.19

- NuGet/Download-BcNuGetPackageToFolder.ps1
- NuGet/Get-BcNuGetPackage.ps1
- ReleaseNotes.txt
Fixes #3318 - check whether any dependencies exists before enumerating them
Add Stacktrace output to high level functions Download-BcNuGetPackageToFolder and Get-BcNuGetPackage
> support no dependencies

- AppHandling/Publish-NavContainerApp.ps1
- Artifacts/Get-BCArtifactUrl.ps1
- ContainerHandling/Invoke-ScriptInNavContainer.ps1
- ReleaseNotes.txt
> Encoding issue with PowerShell 7.4.1

- ContainerHandling/New-NavContainer.ps1
- ContainerHandling/New-NavImage.ps1
Fix bugs after new generic image
> fix new image bugs

- AzureAD/New-AadAppsForBc.ps1
As described in issue [3339](https://github.com/microsoft/navcontainerhelper/issues/3339).
The casing causes the command to fail.
I changed both local vars to start on all places with a non capital to solve the issue which will make the command fail
> Changed local variable casing

- NuGet/Download-BcNuGetPackageToFolder.ps1
- ReleaseNotes.txt
> issue 3347

- HelperFunctions.ps1
- ReleaseNotes.txt
> issue #3349

- AppHandling/Run-TestsInNavContainer.ps1
- ReleaseNotes.txt
> force array

- Api/Invoke-NavContainerApi.ps1
- Bacpac/Export-NavContainerDatabasesAsBacpac.ps1
- ReleaseNotes.txt
> issue #3407

- ContainerHandling/New-NavContainer.ps1
- ReleaseNotes.txt
> issue 3415

- ContainerHandling/New-NavContainer.ps1
- ReleaseNotes.txt
> issue #3444

- ContainerHandling/Get-BestGenericImageName.ps1
- ReleaseNotes.txt
> issue #3454

- HelperFunctions.ps1
- ReleaseNotes.txt
> Issue 3354

- ContainerHandling/New-NavContainer.ps1
- ReleaseNotes.txt
> Issue 3460

- AppHandling/Clean-BcContainerDatabase.ps1
- AppHandling/Compile-AppInNavContainer.ps1
- Bacpac/Backup-NavContainerDatabases.ps1
- Bacpac/Export-NavContainerDatabasesAsBacpac.ps1
- Bacpac/Restore-DatabasesInNavContainer.ps1
- ContainerHandling/New-NavContainer.ps1
- HelperFunctions.ps1
- Misc/Set-BcContainerFeatureKeys.ps1
- TenantHandling/New-NavContainerTenant.ps1
- UserHandling/New-NavContainerNavUser.ps1
1.0.2.20 now has SqlServer PS module preinstalled on PS 7 + compatible overrides
> remove usepwsh false and require 1.0.2.20

- ContainerHandling/Invoke-ScriptInNavContainer.ps1
> issue #3507

- Artifacts/Download-Artifacts.ps1
- BC.HelperFunctions.ps1
- Common/Download-File.ps1
- HelperFunctions.ps1
Downloading artifacts would hang forever some times.
> fix download timeout

- AppHandling/Compile-AppInNavContainer.ps1
- ContainerHandling/New-NavContainer.ps1
- Misc/Copy-FileToNavContainer.ps1
- ReleaseNotes.txt
> regressions

- .github/workflows/CI.yaml
- .github/workflows/Release.yaml
Move publishing of containerhelper to federated credentials
Related to AB#535824
> Move publishing of containerhelper to federated credentials

- ContainerHandling/New-NavContainer.ps1
- README.md
1. **Windows 11 Setup Issues:**
- Noted that the command `Install-WindowsFeature Containers -Restart` is only applicable to Windows Server, not Windows 11.
- Highlighted that Docker Desktop is set up for Linux containers by default, even if Hyper-V is selected instead of WSL.
2. **Guidance for Docker Desktop Users:**
- Added a hint in New-NavContainer.ps1 to switch to Windows containers if Docker Desktop is installed, ensuring proper configuration.
3. **Generic Images Section:**
- Added a new generic image section, based on @freddydk's recent LinkedIn post, to give users more information about how the generic image is selected.
4. **Overview of Isolation Differences:**
- Provided a detailed comparison between Hyper-V and Process isolation containers, clarifying their differences in terms …
> Readme.md improved

- AppHandling/Copy-AlSourceFiles.ps1
- AppHandling/Run-AlCops.ps1
- BC.HelperFunctions.ps1
- ReleaseNotes.txt
Issue 3544 Copy-AlSourceFiles.ps1 does not copy RDLC and DOCS Files with the new report layout definition
Issue 3550 Run-AlValidation is checking wrong runtime version
Issue 3555 Increase default timeout
Fixes #3544
Fixes #3550
Fixes #3555
> 3 small bug fixes

- AppHandling/Run-AlPipeline.ps1
- Auth/New-BcAuthContext.ps1
- Auth/Renew-BcAuthContext.ps1
- ReleaseNotes.txt
Fixes https://github.com/microsoft/AL-Go/issues/1093
Support for federated credentials in New-BcAuthContext
> generateDependencyArtifact doesn't work when useCompilerFolder is true

- AppHandling/Run-AlPipeline.ps1
> issue #3565

- CompilerFolderHandling/New-BcCompilerFolder.ps1
- ReleaseNotes.txt
> issue #3617

- .github/workflows/CI.yaml
- .github/workflows/Release.yaml
- BcContainerHelper.psd1
- ContainerHandling/New-NavImage.ps1
- NavContainerHelper.md
- NuGet/Get-BcNuGetPackageId.ps1
- README.md
- ReleaseNotes.txt
Already done in nav-docker and nav-arm-templates
> rename master branch to main

- CompilerFolderHandling/Compile-AppWithBcCompilerFolder.ps1
- ReleaseNotes.txt
> Issue #3660

- AppHandling/Compile-AppInNavContainer.ps1
- AppHandling/Run-AlPipeline.ps1
- HelperFunctions.ps1
- NuGet/Publish-BcNuGetPackageToContainer.ps1
NuGet feeds didn't work when using Containers / FilesOnly Containers
> Nuget fixes

- BC.HelperFunctions.ps1
- NuGet/NuGetFeedClass.ps1
- ReleaseNotes.txt
> Check user or org

- AppHandling/Run-AlCops.ps1
- AppHandling/Run-AlPipeline.ps1
- AppHandling/appsource.default.ruleset.json
- NuGet/Download-BcNuGetPackageToFolder.ps1
- ReleaseNotes.txt
Fixes #3666 
Add appSource.default.ruleset.json to BcContainerHelper and use from there.
> Add ruleset to BcContainerHelper and use from there

- AppHandling/Compile-AppInNavContainer.ps1
- CompilerFolderHandling/Compile-AppWithBcCompilerFolder.ps1
- ReleaseNotes.txt
- Saas/Publish-PerTenantExtensionApps.ps1
> Regression + test failure

- AppHandling/Run-AlPipeline.ps1
Fixes https://github.com/microsoft/AL-Go/issues/1291
> Fix AL-Go bug 1291

- AppHandling/Publish-NavContainerApp.ps1
- ReleaseNotes.txt
> Hacky temp workaround for #3591

- NuGet/Get-BcNuGetPackageId.ps1
- ReleaseNotes.txt
> Fix for name length

- AppHandling/Copy-AlSourceFiles.ps1
> Fix for Copy-AlSourceFiles.ps1 missing reportextension and profileextension type

- AppHandling/Run-AlPipeline.ps1
- ReleaseNotes.txt
Fixes https://github.com/microsoft/AL-Go/issues/1405
> Check whether testapps are installed

- AppSource/Invoke-IngestionAPI.ps1
The PR https://github.com/microsoft/navcontainerhelper/pull/3852 caused a syntax error, which I didn't catch in code review
> fix syntax error

- AppHandling/Run-AlPipeline.ps1
- CompilerFolderHandling/New-BcCompilerFolder.ps1
- HelperFunctions.ps1
Remove irritating log lines
Use a working version of bc-replay when installing
> remove irritating logs and use a working version of bc-replay

- AL-Go/New-ALGoAppSourceContext.ps1
- AppSource/Invoke-IngestionAPI.ps1
- ReleaseNotes.txt
Fixes https://github.com/microsoft/AL-Go/issues/1519
> AL Go issue 1519

- CompilerFolderHandling/New-BcCompilerFolder.ps1
- ReleaseNotes.txt
Fixes https://github.com/microsoft/AL-Go/issues/1640
> remove invalid template

- HelperFunctions.ps1
- ReleaseNotes.txt
> Issue 3886 - Trim url

- AppHandling/Clean-BcContainerDatabase.ps1
- AppHandling/Compile-AppInNavContainer.ps1
- ReleaseNotes.txt
fixes https://github.com/microsoft/AL-Go/issues/1713
> Don't use -symbolsOnly flag in BC 27 (no longer supported)

- AppHandling/Sign-NavContainerApp.ps1
- Artifacts/Download-Artifacts.ps1
- ContainerHandling/New-NavContainer.ps1
Route traffic through AFD endpoint rather than directly to the storage account
> Route traffic through AFD endpoint

- TenantHandling/New-NavContainerTenant.ps1
Add missing comma to New-NavContainerTenant
> Add missing comma to New-NavContainerTenant

- AppHandling/Run-AlPipeline.ps1
- ReleaseNotes.txt
Parameterize NPX replay call and add some logging 
microsoft/AL-Go#1920
> Parameterize NPX replay call and add some logging 
