microsoft/navcontainerhelper

ContainerHandling/Enter-NavContainer.ps1
Instead of having a prompt like this:
`[50f1bdc0752b173da826a718e20d3c4d08a041d9a0924f7f39cc221ea9137e22]: PS C:\run>`
this looks way better:
`[NAVDEMO]: PS C:\run>`
=> Show container name in prompt when in remote session

ContainerHandling/New-NavContainer.ps1
To prevent the RTC client from using the shared **clientusersettings.config** file (in _%appdata%\Microsoft\Microsoft Dynamics NAV\110_), 
we should provide the argument **-settings:ClientUserSettings.config**.
This way the shortcut always works even when working with multiple containers on the same machine.
=> Use settings file for RTC client desktop shortcut

Bacpac/Export-NavContainerDatabasesAsBacpac.ps1
By default the database 'tenant' is being exported - this is the template tenant.
Any changes done in the container (Default database) are never included in the exported tenant bacpac.
In our case we want to maintain our setup/sample data in a Docker container and at some point export this data and use it for new deployments.
Note: this only applies to multi-tenant containers.
=> Added possibility to choose which tenant database to export when exporting bacpacs

HelperFunctions.ps1
=> fix: Write error if docker command fails instead of red message

AzureAD/Create-AadAppsForNav.ps1
Get-AzureADUser only retrieves the first 100 users, if you're unlucky you're outside those 100 users, this causes an error.
Can be solved in two ways:
- Add the -All $true parameter to the Get-AzureADUser cmdlet.
- Filter up front by using the -ObjectId parameter so that it only retrieves that specific user instead of all the users.
I implemented the latter.
=> [Bugfix] Create-AadAppsForNav - Get-AzureADUser only retrieves the first 100 users.

ObjectHandling/Import-TestToolkitToNavContainer.ps1
This change allows you to import the TestToolkit objects for a specific country in the event there are multiple sets of country-specific objects, such as what ships in the North American images. As an example, you can import and run the Canadian tests and then import and run the US tests to ensure tests pass in all localizations.
=> Import test toolkit filtering

AppHandling/Publish-NavContainerApp.ps1
New parameters in Publish-NavContainerApp:
- scope - to enable publish and install as tenant extension, which is similar to how AL extension in VS Code works.
- syncMode - to enable Add, Clean or Development mode for database schema synchronization. The default sync mode used by VS Code is Development, to enforce database synchronization without increasing the version number of the app.
=> Add parameters scope and syncMode

AppHandling/Convert-CALTestOutputToAzureDevOps.ps1
On none English servers the function generates "Time"-Values like "260,336" which will be interpreted by DevOps as 3 days instead of 4 minutes.
The added parameter will ignore the local format and always export with "." (dot) as decimal marker.
=> fixed format for servers with different culture

AppHandling/Compile-AppInNavContainer.ps1
if the app publisher is the company and the comapany name is like "GmbH & Co. KG" the web request fails
=> EscapeDataString for $publisher to handle "&"

AppHandling/Convert-ALCOutputToAzureDevOps.ps1
Added case to report error to DevOps for ALC internal errors like:
`error AL0999: Internal error: System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException...`
=> DevOps error detection ALC internal error

ContainerHandling/Invoke-ScriptInNavContainer.ps1
There was a problem when using Invoke-ScriptInNavContainer in a non-admin session. If one of the params contained apostrophes (i.e. $param = "UPDATE xxx SET `"Field A`" = '' " ), the temporary script file that was created contained a xml string with unescaped apostrophes. When running the temporary script file the xml string wasn't completly interpreted, resulting in an missing apostrophe in the param. This is now fixed by converting the whole XML to base64, which is converted back before the xml string is loaded.
=> Invoke-ScriptInNAVContainer fix - use base64 for arguments

AppHandling/Create-AlProjectFolderFromNavContainer.ps1
Container variable name in script was $imageName that did not exist. Fixed variable name to $containerName
=> Fix container variable name in Create-AlProjectFolderFromNavContainer

CompanyHandling/Get-CompanyInNavContainer.ps1
The output of Get-CompanyInNavContainer includes any warning lines that are returned by PowerShell e.g. licence about to expire, licence not compatible.
Added a Where to remove those lines. I guess this may be a problem for other commands as well but I'm not sure how you'd filter them out without changing each place Invoke-ScriptInNavContainer is called from.
=> Ignore WARNING lines when getting companies

ContainerHandling/New-NavContainer.ps1, ContainerHandling/Setup-TraefikContainerForNavContainers.ps1, ContainerHandling/traefik/CheckHealth.ps1, ContainerHandling/traefik/template_traefik.toml, NavContainerHelper.psm1
This allows creating a new NAV container with the necessary settings and labels for Traefik as explained here https://www.axians-infoma.com/techblog/running-multiple-nav-bc-containers-on-an-azure-vm/
With the PR in place you can create a new container reachable through Traefik as easy as this:
```
New-NavContainer -accept_eula -containerName imau -imageName mcr.microsoft.com/businesscentral/onprem:de -useTraefik
NavContainerHelper is version 0.0
Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
Docker Client Version is 18.09.4
Docker Server Version is 18.09.4
Using image mcr.microsoft.com/businesscentral/onprem:de-ltsc2019
PublicDnsName is traef-test10.westeurope.cloudapp.azure.com
Creating Nav container imau
Version: 14.0.29537.0-de
Platform: 14.0.29530.0
Generic Tag: 0.0.9.5 …
```
=> Add Traefik support

ContainerHandling/Setup-TraefikContainerForNavContainers.ps1, ContainerHandling/traefik/template_traefik.toml
Hi dear maintainers, thanks for this cool piece of software!
After discovering this projects thanks to the blog posts of @tfenster (https://www.axians-infoma.de/techblog/traefik-support-for-navcontainerhelper-the-nav-arm-templates-for-azure-vms-and-local-environments/), I wanted to propose some practises we recommend to Traefik users.
This PR introduces the following changes:
- Fix the version of Traefik. As the version 2.0 is [in alpha version and would have breaking changes](https://blog.containo.us/back-to-traefik-2-0-2f9aa17be305), better fixing the version by using docker tag, as Stefan is doing an awesome work by maintaining a Windows Docker image with a lot of tags.
- Cost of this change is that this version should be updated to follow Traefik.
- Fix a deprecated configuration in …
=> Improve Traefik usage: fixed version + improved security for the UI

ContainerHandling/Setup-TraefikContainerForNavContainers.ps1
This allows to use a custom instead of the default one. 
Also you can use your certificate for your own domain.
For using your certificate the toml has to look like this:
debug = false
defaultEntryPoints = ["https","http"]
[entryPoints]
[entryPoints.http]
address = ":80"
[entryPoints.http.redirect]
entryPoint = "https"
[entryPoints.traefik]
address = ":8080"
[entryPoints.https]
address = ":443"
[entryPoints.https.tls]
[[entryPoints.https.tls.certificates]]
certFile = "c:/etc/traefik/certificate.crt"
keyFile = "c:/etc/traefik/certificate.key"
[docker]
domain = "$PublicDnsName"
watch = true
endpoint = "npipe:////./pipe/docker_engine"
[api]
entryPoint = "traefik"`
=> Improve Traefik: Use custom toml and certificate for own domain

ContainerHandling/Invoke-ScriptInNavContainer.ps1, ReleaseNotes.txt
Support AccessToken as Office365Password instead of the AAD User Password (to allow MFA accounts)
Invoke-ScriptInNavContainer automatically switches to docker exec if new-pssession fails
=> AccessToken and Invoke-script

AppHandling/Convert-ALCOutputToAzureDevOps.ps1
PTE errors has  three letters, not two as others.
"error PTE0001" instead of "error AL0001"
This little change catches error codes with two or three letters and four numerics.
=> Catch errors from PTE CodeCop

AppHandling/ClientContext.ps1
I added a few lines to help troubleshoot the kind of strange errors as in #617 
If there are an InnerException available, it will be printed. 
Maybe it would be nicer to do it by recursion and only write the exception messages, but now I at least see all inner exceptions.
The text when getting theese error would then be something like below, with several levels of InnerExceptions:
```
CommunicationError : An error occurred while sending the request.
CommunicationError InnerException : System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80
at …
```
=> Write InnerExceptions if available

Api/Invoke-NavContainerApi.ps1
This change allows to do request with special characters like ä, ö, ü in the body.
Without this change the following command will fail:
```
$packageId = "Änderungsprotokoll"
Invoke-BCContainerApi -containerName $containerName `
-CompanyId $CompanyId `
-credential $credential `
-APIPublisher "microsoft" `
-APIGroup "automation" `
-APIVersion "v1.0" `
-Method "POST" `
-Query "configurationPackages"  -tenant default `
-body @{ "code" = $packageId; "packageName" = $packageId; } | Out-Null
```
Error:
```
Unable to translate bytes[*] at index * from specified code page to unicode.
```
=> Fix encoding for local special chars (mutated vowel, umlauts)

ContainerHandling/Setup-TraefikContainerForNavContainers.ps1
The given 'exit' will couse the ISE to quit and the user will not be able to see the message that traefik is already initialized.
Maybe we should also change the Write-Host into a Write-Warning. What do you think?
=> exit function with 'return' instead of 'exit'

ContainerInfo/Get-NavContainerPath.ps1
Get-NavContainerPath didnt find any paths, which were subfolders of a shared folder. The reason for that was, that in this case the comparison failed because a double backslash in the path added in line 41. See screenshot.
=> Added Join-Path instead of "+" to prevent broken paths

AppHandling/Compile-AppInNavContainer.ps1
Useful functionality when repository has multiple apps.
=> Add CopyAppToSymbols to Compile-App

AppHandling/Convert-ALCOutputToAzureDevOps.ps1
`Test-Path` with a null Path parameter fails with error `Cannot bind argument to parameter 'Path' because it is null.`
I don't really understand why `Test-Path $Matches[3]` is used. 
But if you wan't to check if there where 2 or 3 matches, checking if `$Matches[3]` is $null should be ok.
This is tested in my pipeline for `warning AS0055: The AppSourceCop configuration must specify the list of countries targeted by the application.` and it seems to do it's thing.
=> Fix issue https://github.com/microsoft/navcontainerhelper/issues/765

ContainerHandling/Invoke-ScriptInNavContainer.ps1
When running Invoke-ScriptInNavContainer unelevated and the scriptblock fails, the Invoke- Script does not throw any error. This causes for example the Publish-NavContainerApp to report success when in fact it failed. 
Simply checking the `$LASTEXITCODE` should solve the issue but maybe theres a bether solution? 
It seems like docker exec is writing errors to stout instead of sterr?
=> Fix Invoke-ScriptInNavContainer when running unelevated

AppHandling/Compile-AppInNavContainer.ps1, AppHandling/Publish-NewApplicationToNavContainer.ps1, AppHandling/Sort-AppFoldersByDependencies.ps1, Tests/AppHandling.ps1
This modification prevents errors due to illegal characters in the app file name that occur when such characters are used in the app name.
Illegal characters are now simply removed from the app file name (which is in line with the behavior of the VSCode AL extension).
=> Fix illegal chars in app file name

ContainerInfo/Get-NavContainerSharedFolders.ps1, NavContainerHelper.psm1
When a container runs as Swarm service, then the volume will appear below Mounts, not below HostConfig.Binds
=> Support swarm services

ContainerHandling/Get-LatestAlLanguageExtensionUrl.ps1
> ##[error]Invoke-WebRequest : The response content cannot be parsed because the Internet Explorer engine is not available, or 
> ##[error]Internet Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again. 
>
=> Avoid error when used on machines without IE Engine (containers, etc).

AppHandling/Compile-AppInNavContainer.ps1, ContainerHandling/New-NavContainer.ps1, ContainerHandling/New-NavImage.ps1, HelperFunctions.ps1, Misc/Download-Artifacts.ps1, ObjectHandling/Convert-Txt2Al.ps1
For better performance use of 7zip instead of Expand-Archive when it's possible - on Azure and GitHub hosted Agents 7zip is installed by default.
I tested it to expand platform artifact and get following result:
- Using Expand-Archive - 57 seconds
- Using Expand-7zipArchive - 8 seconds
In case that 7zip tool is not found - system will use standard Expand-Archive function.
=> Use 7zip if exist to expand archive

AppHandling/Run-AlPipeline.ps1, AppHandling/Sort-AppFilesByDependencies.ps1, ReleaseNotes.txt
Allow AppFiles to be an empty array in Sort-AppFilesByDependencies
Allow previousApps to be present locally (not downloaded from http or https)
=> AppFiles and PreviousApps fix

ContainerHandling/New-NavImage.ps1
According to line 16, the default should be 8G. We ran into OutOfMemory issues when creating images with test libraries installed, so I think the documented behavior is better than the implemented one, so I would propose to change the implementation, not the documentation
=> Fix inconsistency with documentation

TenantHandling/New-NavContainerTenant.ps1
The parameter **$allowAppDatabaseWrite** must be passed as param to the script block. Otherwise, the variable in allowAppDatabaseWrite script block will be always $false. Same behavior as with the switch doNotCopyDatabase.
=> Bug Fix: Param allowAppDatabaseWrite added to script block

ContainerHandling/Setup-TraefikContainerForNavContainers.ps1
Since Docker is starting to enforce pull limitations it makes sense to check if the image is already up to date instead of pulling every time.
=> Check Traefik image before pulling

AppHandling/ClientContext.ps1, AppHandling/Run-AlValidation.ps1, ReleaseNotes.txt
Run-AlValidation use single tenant containers by default for performance
Add resilience to ClientContext::GetAllForms
=> -multitenant + resillience in getallforms

ContainerHandling/New-NavContainer.ps1
Since Client Services are not mapped via Traefik we should be able to specify the port we want to use.
=> Remove check for clientservicesport

ContainerHandling/Import-NavContainerLicense.ps1
When I setup an Azure Devops Pipeline and followed the tutorial by @freddydk I had issues with dropbox providing an empty file. The error message displays a misleading message. I added more value to the error messages to improve error deduction
=> Improve error message handling for license download

ContainerHandling/Setup-TraefikContainerForNavContainers.ps1
The Traefik docker image was about 2 years old and from an unofficial and no longer updated source. Since then there have been 16 maintenance releases. By changing this to the current 1.7 Windows release from the official repo fixes such as minor tls and docker api updates will get automatically applied until support for the 1.7 version runs out. See all changes [here](https://github.com/traefik/traefik/blob/v1.7/CHANGELOG.md).
I have tested this out on a dev environment while trying to find an unrelated problem in our setup a month back and have seen no side effects to this change.
if a "latest"1.7 image is not wanted for fear of a future update breaking production environments, `traefik:v1.7.28-windowsservercore-1809` would also work.
=> Change Traefik docker image to use the official 1.7 release

AppHandling/Run-AlCops.ps1, AppHandling/Run-AlValidation.ps1, ReleaseNotes.txt
Run-AlValidation doesn't fail getting the same app in apps and previousApps (if apps in the middle of the dependency chain hasn't changed)
Run-AlCops doesn't use previousApp if it is the same version as the app
=> Support same previousapp

BcContainerHelper.psm1, ContainerHandling/New-NavContainer.ps1, ContainerHandling/traefik/Add-DomainToTraefikConfig.ps1
As described in issue #1867 when creating mutliple traefik containers using the same public dns name (e.g. `bc.domain.com`) all containers will get the first part of the public dns name as hostname (e.g. `bc`). This leads to HealthCheck issues and the server instances are battling against each other. The result of this is that a user get kicked out really fast (after a few seconds of inactivity). It also seems to make the complete environment extremely slow.
The problem can be solved by two ways:
1. Create subdomains for each container so every container will get a unique hostname
2. Remove the link in between public dns name and hostname
Option 1 is leading to another problem. With `Setup-TraefikContainerForBcContainers` you specify _**one**_ public dns name for which the acme challenge …
=> Running multiple traefik containers using same external database

HelperFunctions.ps1
Fix an **Expand-7zipArchive** helper function issue with parsing 7-Zip version information.
Tested with 7-Zip version: **"21.01 alpha"**.
This pull request is for this issue: #1913
=> Fix issue with parsing version information for alpha versions of 7-Zip

AppHandling/Compile-AppInNavContainer.ps1
The new `generatecrossreferences ` flag is only supported by alc-compilers in BC18 and newer.
Older compilers will fail if the parameter is supplied.
=> Added minimum version for generatecrossreferences

BcContainerHelper.psm1
As Ukraine localization is developed by partners and is w1-based, it is necessary to add this mapping to run Run-ALValidation.
(Rest of changes seems to be due to mixed line endings.)
#2029
=> Add ukraine to w1 mapping

AppHandling/Compile-AppInNavContainer.ps1, AppHandling/Run-AlPipeline.ps1
This pull requests adds a new param to the Compile-AppInBcContainer so one or more Custom code cop's can be used when compiling apps.
This feature is following the same design as the Ruleset, the .dll file needs to be in the directory that is copied to the container in order to be used.
Also I tried to match the coding & documenting style.
=> Added parameter for a Custom Code Cop to Compile-AppInBcContainer

AppHandling/Run-AlPipeline.ps1
Per runtime version 7.2 applicationInsightsKey is being deprecated by Microsoft (see link below). This change supports the replacement: **applicationInsightsConnectionString**
Microsoft Link: [https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-json-files](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-json-files)
=> Support applicationInsightsConnectionString in app.json

AppHandling/UnPublish-NavContainerApp.ps1
When an app exists in the with the same version in multiple tenants it's impossible to unpublish with the bccontainerhelper.
The condition here doesn't work when a list is returned by Get-NAVAppInfo.
I'm not sure if there is a better way to test if 'scope' exists in the list but I also can't see a scenario where the property doesn't exist.
=> fix multitenant unpublish

AppHandling/Publish-NavContainerApp.ps1
Add Documentation for upgrade parameter.
If upgrade is not needed just install the app. this helps when the user just wants to have the app running but doesn't know if an upgrade is necessary or not. just always publish with the upgrade parameter and then the app is ready in any case.
=> Improve Upgrade Handling while publishing an App

ObjectHandling/Import-TestToolkitToNavContainer.ps1
Hi Freddy, we are experiencing issues with function Import-TestToolkitToBcContainer in multi-tenant containers.
Below is the command to reproduce the issue in a multi-tenant container.
**Command:**
```
Import-TestToolkitToBcContainer $ContainerName -includeTestLibrariesOnly -tenant $TenantId -scope Tenant -ImportAction Overwrite
```
**Error output details:**
```
Synchronizing Test Runner on tnt1
App successfully synchronized
Installing Test Runner on tnt1
App successfully installed
Synchronizing Any on tnt1
App successfully synchronized
Installing Any on tnt1 …
```
=> fix for error: No published package matches the provided arguments.

ObjectHandling/Invoke-NavContainerCodeunit.ps1
Hi Freddy,
With BC19 release, Invoke-NavContainerCodeunit.ps1 is now throwing an error on Line#73 (Remove-NAVServerUser).
I am not sure why do we need to remove the `user manager\containeradministrator` user in the first place. We can just choose to keep the user and disable it when it's not needed.
With this PR, I am eliminating the Remove-NAVSeverUser command altogether while fixing the Set-NAVServerUser at the end of CodeUnit execution.
Also, before the CodeUnit execution starts, I am setting the user's company as passed in parameters, just in case it's significant.
**Error in BC19:**
```
WARNING: Import Successful
You must choose a company before you can access the "User Login" table.
at <ScriptBlock>, <No file>: line 28
at Invoke-ScriptInBcContainer, C:\Program …
```
=> Remove-NAVServerUser fix while Invoking CodeUnits

AppHandling/Run-AlPipeline.ps1
=> Preserve special characters in app.json

AppHandling/Run-AlPipeline.ps1
In the old implementation, files with more than one disabled test would be converted to an array of array. 
disabledTests.json:
```json
[
{
"codeunitName":  "lbt TestSales",
"method":  "Sales_Test_GlEntry"
},
{
"codeunitName":  "lbt TestSales",
"method":  "Sales_Test_GlEntry"
}
]
```
Result (converted back to json for readability):
```powershell
PS C:\WINDOWS\system32> $disabledTests | ConvertTo-Json
{
"value":  [
{
"codeunitName":  "lbt TestSales",
"method":  "Sales_Test_GlEntry"
},
{
"codeunitName":  "lbt TestSales",
"method":  "CreateProdOrderfromSales"
}
],
"Count":  2
}
```
This would break the skipping of tests i.e. the test would still be run.
```powershell
PS C:\WINDOWS\system32> Run-TestsInBcContainer runtest3 -credential $credential -extensionId …
```
=> Fix ignore disabled Tests

ContainerHandling/New-NavContainer.ps1, ReleaseNotes.txt
Based on https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=1496929793343488, I tried to implement AAD authentication for dev usage. With the help of @kalberes and @SBalslev I could get it up and running, but the VS Code AL extension creates a bearer token with audience https://api.businesscentral.dynamics.com when e.g. downloading symbols. Therefore, we need to add that to the valid audiences as well. If and when that behavior is changed, we could remove it again. Setting it via customNavSettings unfortunately doesn't work as those are first evaluated and then [this](https://github.com/microsoft/navcontainerhelper/blob/26de82557f34c5e1fab8568312c235b390b2a89f/ContainerHandling/New-NavContainer.ps1#L1478) overrides them. On startup it looks like this:
```
PS …
```
=> Fix problems with AAD authentication against dev endpoint

PackageHandling/Resolve-DependenciesFromAzureFeed.ps1, ReleaseNotes.txt
In runtime 4.0 and lower the app id is present with the the property appId and not id.
https://github.com/microsoft/navcontainerhelper/blob/89c424816ab8c4ae6cfd5f903d50cb24da00cb4e/AppHandling/Extract-AppFileToFolder.ps1#L165-L176
=> App Resolutions not working correctly with lower runtimes.

AppHandling/Extract-AppFileToFolder.ps1, ReleaseNotes.txt
**Problem:**
When running Run-AlValidation, some feature flags from the app.json are ignored causing compilation failures later on.
**Solution:**
Update the list of support feature flags.
=> Update list of feature flags for Extract-AppFileToFolder

ContainerHandling/updatehosts.ps1, ReleaseNotes.txt
Had issues with building a new container with use of external SQL.  Found out that I had some whitespaces in my hosts file.
This resolves the issue.
handles following example lines in hosts file.  (without " of course)
"    192.168.1.190  host.docker.internal  "
"192.168.1.190          host.docker.internal"
=> allow whitespaces around IP and Hostnames in hosts file.

AppHandling/Get-NavContainerAppInfo.ps1
This PR adds an `-appFilePath` parameter to the `Get-BcContainerAppInfo` function.
This parameter is passed as the `-Path` parameter for the `Get-NAVAppInfo` CmdLet.
For this parameter the `-ServerInstance` parameter should not be passed (this would result in an error).
We were currently missing this parameter set as an option in the BcContainerHelper module.
Please let me know if you have any comments on the implementation.
(Opening a new PR as https://github.com/microsoft/navcontainerhelper/pull/2426 was closed by @freddydk)
=> Add appFilePath param to Get-BcContainerAppInfo

PackageHandling/Publish-BuildOutputToAzureFeed.ps1
If the RuntimePackage folder is no present an error is thrown.
=> Fix bug if RuntimePackages are not present

ContainerInfo/Get-NavContainerEventLog.ps1
This introduces a fix to the bug mentioned in issue #2581 by using wevtutil's archive functionality to preserve the display information of the container's OS.
=> Archive evtx file to preserve display information

CreateALGoRepo.ps1
```
The property 'additionalCountriesAlway' cannot be found on this object. Verify that the property exists.
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\4.0.2\CreateALGoRepo.ps1:1154 char:36
+ ... Countries @($settings.additionalCountries.Split(',') | ForEach-Object ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : PropertyNotFoundStrict
```
=> Fix AdditionalCountriesAlways typo

BcContainerHelper.psm1
As reported in #2713, there seems to be an issue at least in some setups on Win Server 2022 to access the docker engine npipe from hyperv containers. As a fix, this uses a traefik image with a variant for Win Server 2022 so that process isolation can be used
=> use traefik image with 2022 support

PackageHandling/Publish-BuildOutputToAzureFeed.ps1, PackageHandling/Resolve-DependenciesFromAzureFeed.ps1
This fixes #2765.
It now checks if `--pat` was set and apply the vaule as the enviroment variable. 
This might still break somebodys pipeline if they passed something random in pat. - I've checked my pipeline and I always passed the enviroment variable in.
If we can't accept this, I could include a check to see if AZURE_DEVOPS_EXT_PAT is empty and only use the parameter if no enviroment variable was set before.
But I think If I pass in a explicit paramter that should be used and not some enviroment variable set somewhere. 
There is no way to pass the pat directly to the function because, authentication is usally done through `azure devops login`.
=> Using unused pat parameter

AppHandling/Copy-AlSourceFiles.ps1
In the us localization (BC21) there are multiple rdlc files with the same name. This gives an error when running "Create-AlProjectFolderFromNavContainer". Fix: First search for a rdlc file in the current folder of the report.
=> Fix multiple layout files with same file name

AppHandling/Compile-AppInNavContainer.ps1
LCG files aren't generated 
Repro Steps:
- Run Compile-AppInBcContainer with `-features @("lcgtranslationfile", "generateCaptions")`
- Compiler is invoked with `/features:System.Collections.ArrayList` instead of `/features:lcgtranslationfile,generateCaptions`
=> Fix for feature formatting 

ContainerHandling/New-NavImage.ps1, ReleaseNotes.txt
Using the New-NavImage/New-BcImage in our Azure DevOps pipelines I would like to expand this function with a new parameter
-   databaseBackupPath: allows selecting custom backup in place of original backup from artifacts
In our case this will save a lot of time in pipelines, because usually we are using custom database that is based on Cronus but contains all of our library apps and config. Now we need to republish all those apps for every build that depends on our library apps (even so our library apps do not change so often), so every build runs 2-5 min. longer than it could. It might not look so much of a time, but we are using pipelines a lot so it easily accumulates to hours of wait time.
With this parameter we could support scenario like this:
- Every month we run pipeline to …
=> Add extra parameters to New-NavImage

AppHandling/Sign-NavContainerApp.ps1
Change the default URL of the timestamp server to match value for timeStampServer in $bcContainerHelperConfig
=> Fix value of default timestamp server in doc comments on Sign-NavContainerApp.ps1

AppHandling/Sign-NavContainerApp.ps1, ContainerHandling/Enter-NavContainer.ps1, ContainerHandling/Get-NavContainerSession.ps1, ReleaseNotes.txt
+ When using Enter-BcContainer in PowerShell 7, the containername prompt was displayed twice
=> Sign without PsSession

AppHandling/Publish-NavContainerApp.ps1
When republishing parent app with dependencies using `Publish-BcContainerApp` with option `-useDevEndpoint` request returns **error 422**:
```
Status Code 422 : Unprocessable Entity
The extension <CHILD EXTENSION NAME> <VERSION> cannot be installed because a newer version <CURRENT VERSION> is already installed.
```
Parent app is published and installed, but all dependent apps are uninstalled. 
If `DependencyPublishingOption` is set to **default** error is not returned and dependencies are not uninstalled.
Therefore I suggest to add new parameter to function.
=> Added dependencyPublishingOption param to Publish-BcContainerApp function

AzureAD/New-AadAppsForBc.ps1, AzureAD/Remove-AadAppsForBc.ps1
I tried to add new cmdlet that supports the new Microsoft.Graph Powershell Module to create the Aad  Apps. (See issue https://github.com/microsoft/navcontainerhelper/issues/2351)
it can be tested with the following commands:
```ps
$bcAuthContext = New-BcAuthContext -tenantID $azureTenantId -clientID $azureApplicationId -clientSecret $clientSecret -scopes "https://graph.microsoft.com/.default"
$AdProperties = New-AadAppsForBc -appIdUri https://mycontainer.mydomain/bc/ -bcAuthContext $bcAuthContext 
```
If there is anything that should be changed, I'm happy to do so. I'm no expert with powershell, therefore there can be some room for improvements.
=> New Cmdlt New-AadAppsForBc using Microsoft.Graph

AppHandling/Convert-ALCOutputToAzureDevOps.ps1
Hi Freddy,
This very small PR adds the ability to parse custom 3 character issue codes from alc output. I tried to find a gap for PTE, but without luck. Please see this as a compatibility PR for custom analyzers :).
Some years back, we decided to implement MCP which is not fully covered by the current implementation. 
Thank you,
Carsten
=> Allow 3 chars for all analyzer rules i.e. PTE1234

ConfigPackageHandling/Get-PackageInfoFromRapidStartFile.ps1
Issue #3051 Unable to import .rapidstart file - The property 'Code' cannot be found on this object
=> Issue #3051 Unable to import .rapidstart file - The property 'Code' cannot be found on this object

AppHandling/Compile-AppInNavContainer.ps1, AppHandling/Get-NavContainerApp.ps1, AppHandling/PsTestFunctions.ps1, AppHandling/Publish-NavContainerApp.ps1, HelperFunctions.ps1
for some reason, it appears ssl validation bypass using System.Net.ServicePointManager does not work with powershell 7
use built-in powershell method Invoke-WebRequest which provide same capabilities
related to #3066
=> fix: enhance ps7 compatibility with ssl selfsigned

NuGet/Get-BcNuGetPackage.ps1
Get-BcNugetPackage doesn't support old Azure DevOps URL format. This change adds it.
=> add support for old devops URL format

AppHandling/Run-AlPipeline.ps1, ReleaseNotes.txt
Add parameters `PreCompileApp` and `PostCompileApp` to `Run-AlPipeline`: script blocks to run before and after compiling an app when setting `useCompilerFolder` switch.
TODO:
=> Add parameters for scripts to run pre and post compilation

AppHandling/Compile-AppInNavContainer.ps1, CompilerFolderHandling/Compile-AppWithBcCompilerFolder.ps1, ReleaseNotes.txt
4 new parameters on Compile-AppInBcContainer and Compile-AppInCompilerFolder:
```
.Parameter SourceRepositoryUrl
Repository holding the source code for the app. Will be stamped into the app manifest.
.Parameter SourceCommit
The commit identifier for the source code for the app. Will be stamped into the app manifest.
.Parameter BuildBy
Information about which product built the app. Will be stamped into the app manifest.
.Parameter BuildUrl
The URL for the build job, which built the app. Will be stamped into the app manifest.
```
=> support buildBy

AppHandling/Run-AlPipeline.ps1, ReleaseNotes.txt
Add 4 new parameters to Run-AlPipeline: SourceRepositoryUrl, SourceCommit, BuildBy and BuildUrl. The value of these parameters will be stamped into the app manifest during compile.
=> 4 new parameters to Run-AlPipeline

ReleaseNotes.txt, Saas/Install-BcAppFromAppSource.ps1
Hi,
i added the option to use the switch "**useEnvironmentUpdateWindow**" in "**Saas/Install-BcAppFromAppSource.ps1**" and changed the scripts logic accordingly.
Using this switch only schedules the install operation and - of course - does not wait for the operation to be finished.
Also added comment in release notes.
Greetings,
Jeremias
=> add logic for using update window at app installation

Common/Download-File.ps1
In our pipelines we have the need to authenticate using Oauth2 since we have a private storage container, we are using your Download-File in the scripts and I do not want to use a SAS token. I did not find any other way than this, perhaps you have another idea that doesn't need a commit? :)
```
$context = New-BcAuthContext -clientID "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" `
-tenantID "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" `
-clientSecret "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" `
-scopes "https://storage.azure.com/.default"
$headers = @{ 
"Authorization" = "Bearer $($context.accessToken)"
"x-ms-version" = "2017-11-09"
}
Download-File -sourceUrl "https://storage.blob.core.windows.net/container/file.file" `
-destinationFile "c:\temp\file.file" `
-headers $headers
```
=> Custom Headers for Download-File

ReleaseNotes.txt, Saas/New-BcEnvironment.ps1
Hi,
I added the switch "getCompanyInfo" to the function "New-BcEnvironment".
This allows users to prevent the script from getting environment information like companies via the Automation API after the environment was created.
Without the switch, the Automation API is called right after the environment was created, which results in an error, since the application used for authentication via S2S has not been set in Business Central yet.
This enables using S2S - Authentication for environment creation.
Greetings,
Jeremias
=> add Switch "getCompanyInfo" to "New-BcEnvironment"

AppHandling/Start-NavContainerAppDataUpgrade.ps1
There is typo in the code, leading to this error when running Start-BcContainerAppDataUpgrade:
```
The term '=' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```
BCContainerhelper version> 5.0.6-preview1069
=> Fixing typo in the code

AppHandling/Compile-AppInNavContainer.ps1, HelperFunctions.ps1
Latest insider artifacts fail building in compilerfolder
`AL-Go action ran: RunPipeline Telemetry Correlation Id: 5f39d8a8-e12d-4443-bbe1-9ffe5b053643
Error: Unexpected error when running action. Error Message: Exception calling "Create" with "2" argument(s): "Could not load file or assembly 'System.IO.Packaging, Version=4.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.", StackTrace: at GetAppInfo, C:\ProgramData\BcContainerHelper\6.0.1-preview1082\BcContainerHelper\HelperFunctions.ps1: line 1154 <- at Compile-AppWithBcCompilerFolder, C:\ProgramData\BcContainerHelper\6.0.1-preview1082\BcContainerHelper\CompilerFolderHandling\Compile-AppWithBcCompilerFolder.ps1: line 178 `
=> Latest insider artifacts fail building in compilerfolder

AppSource/New-AppSourceSubmission.ps1, ReleaseNotes.txt
fixes #3220 
Hi Freddy,
new AppSource guidelines seem to support hotfixes only when the app version in the offer properties stays untouched.
I thought about reusing the check Param, but the naming would be a bit off.
I tested this with an offer and the hotfix went through validation now.
What do you think?
=> Add Param dotNotUpdateVersionNumber to New-AppSourceSubmission

CompilerFolderHandling/Compile-AppWithBcCompilerFolder.ps1
Remove Out-String for alcCmd return result for correct working Convert-ALCOutputToAzureDevOps
@freddydk this is PullRequest for #3235
=> Fix CompileResult Format in Compile-AppWithBcCompilerFolder

ContainerInfo/Get-NavContainerEventLog.ps1
The previous call "[Diagnostics.Process]::Start($eventLogName)"  could not open evtx files correctly inside PowerShell 7.
Fixes #3248
=> Use Start-Process for Get-BcContainerEventLog

AppHandling/Run-AlPipeline.ps1, ReleaseNotes.txt
Add new switch on `Run-AlPipeline`, `enableCodeAnalyzersOnTestApps`, to enable CodeCops and other code analyzers on test apps.
With these changes, the same analyzer-related settings will be used for both apps and test apps when running `Run-AlPipeline`.
=> Add enableCodeAnalyzersOnTestApps switch to Run-AlPipeline

Saas/Publish-PerTenantExtensionApps.ps1
@freddydk Added filling in companyName no matter if it is added as parameter in Publish-PerTenantExtensionApps.ps1. Empty companyName could give issues, so in my opinion it should be not empty. Before the change if someone don't add the parameter then the next line of code:
`Write-Host "Company '$companyName' has id $companyId"`
is missing companyName.
=> companyName should be filled in if it is not assigned in parameter

AppHandling/Compile-AppInNavContainer.ps1, AppHandling/Run-AlCops.ps1, ContainerHandling/New-NavContainer.ps1
Fixes #3301
JIT install dotnet in filesonly containers
Use dotnet framework version of codeanalysis (if it exists)
skip warning unless updatesymbols is set
=> add dotnet to filesonly

NuGet/New-BcNuGetPackage.ps1
BC14 (runtime 3.0) does not use `id` as JSON key for the dependencies. Instead `appId` is used. `New-BcNuGetPackage` expects `id` key, which results in the following error:
```cmd
2024-01-24T09:17:47.2437517Z ##[error]ForEach-Object : Die Eigenschaft "id" wurde für dieses Objekt nicht gefunden. Vergewissern Sie sich, dass die 
Eigenschaft vorhanden ist.
In C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.4\NuGet\New-BcNuGetPackage.ps1:192 Zeichen:37
+             $appJson.dependencies | ForEach-Object {
+                                     ~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [ForEach-Object], PropertyNotFoundException
+ FullyQualifiedErrorId : PropertyNotFoundStrict,Microsoft.PowerShell.Commands.ForEachObjectCommand
```
Additionally the …
=> Fix New-BcNuGetPackage for Runtime 3.0 (BC14)

AppHandling/Publish-NavContainerApp.ps1, AppHandling/Replace-DependenciesInAppFile.ps1, HelperFunctions.ps1, ReleaseNotes.txt
Include Microsoft_Business Foundation Test Libraries.app when importing test libraries (and tests)
Include Microsoft_System Application Test.app and Microsoft_Business Foundation Tests.app when importing tests
Bug when running Publish-BcContainerApp against a cloud container ($authContext not defined)
Remove the need for a Container when using Replace-DependenciesInAppFile (containername parameter is now obsolete)
=> Problem in Next Major

AppHandling/Sort-AppFilesByDependencies.ps1, BC.HelperFunctions.ps1, NuGet/Download-BcNuGetPackageToFolder.ps1, NuGet/Find-BcNuGetPackage.ps1, NuGet/NuGetFeedClass.ps1, ReleaseNotes.txt
Two new parameters on Sort-AppFilesByDependencies (includeSystemDependencies and includeDependencyVersion)
Add Public Microsoft NuGet Feeds as settings constants
Fix issues in Download-BcNuGetPackageToFolder, where extensive amounts of NuGet searches was performed to locate packages
Download-BcNuGetPackageToFolder now returns an array of apps downloaded instead of True/False
=> NuGet fixes

ContainerHandling/New-NavContainer.ps1, ReleaseNotes.txt
BC 24.0 will require PS7.4.1 to be installed in containers
=> JIT install ps7

ContainerHandling/Get-NavContainerSession.ps1
When using Pws 7.0, this command fails and rest of the code will fix this by using WinRM. 
When using transcript functionality to log output of scripts, the log is flooded by errors from this line even when it is handled by try-catch:
```
PS>TerminatingError(New-PSSession): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The input ContainerId xxxx does not exist, or the corresponding container is not running."
```
=> Ignore error of New-PSSession -ContainerId

AppHandling/Get-NavContainerAppInfo.ps1
In BCApps we use Get-BcContainerAppInfo  to get a sorted list of apps so we can uninstall them in the right order. In the latest artifacts they are not sorted in the right order though
See failures in: 
https://github.com/microsoft/BCApps/actions/runs/8015836387
or 
https://github.com/aholstrup1/BCApps/actions/runs/8023595403
With this change, the build passes again
https://github.com/aholstrup1/BCApps/actions/runs/8023619694
=> NextMajor fixes: Sorting is broken in Get-BcContainerAppInfo 

AppHandling/Run-AlPipeline.ps1
While the password is harmless, it's undesirable to have secrets in logs.
=> Mask password value in Run-ALPipeline logs

BcContainerHelper.psm1
Solves #3378 by catching the specific error and continue.
This is the output of `New-BcContainer` when running as administrator and having the mentioned issue with `Get-WindowsOptionalFeature -online`:
```
BcContainerHelper is running as administrator
Cannot check Hyper-V status.
HyperV is
```
At least we do not stop anymore with this.
=> Resiliency for Get-WindowsOptionalFeature

CompilerFolderHandling/New-BcCompilerFolder.ps1
Fixes a concurrency issue when multiple processes try to use New-BcCompilerFolder with the -vsixFile Parameter
We use multiple build agents on our build server(s). In high concurrency scenarios like parallel build stages we encounter locking issues when multiple builds try to download the vsix file, because all processes try to save the vsix-tempfile to the same location.
```
Using https://ms-dynamics-smb.gallerycdn.vsassets.io/extensions/ms-dynamics-smb/al/12.6.936426/1707296229269/Microsoft.VisualStudio.Services.VSIXPackage
New-BcCompilerFolder Telemetry Correlation Id: d40bb062-056f-4a96-a47c-8cbee117ac0b
##[error]Remove-Item : Cannot remove item C:\Users\TfsBuild\AppData\Local\Temp\alc.zip: The process cannot access the file 
'C:\Users\TfsBuild\AppData\Local\Temp\alc.zip' because it …
```
=> Fix concurrent vsixFile download in New-BcCompilerFolder

BC.HelperFunctions.ps1, ContainerHandling/Get-BestGenericImageName.ps1, ReleaseNotes.txt
This fix causes everybody to default to ltsc images of Business Central instead of images using specific version numbers.
All Windows versions before Windows Server 2019 will default to **mcr.microsoft.com/businesscentral:ltsc2016** which always is the latest Windows Server 2016 version.
All Windows Server 2019 versions and after (+ before Windows Server 2022) will default to **mcr.microsoft.com/businesscentral:ltsc2019** which always is the latest Windows Server 2019 version
All Windows Server 2022 and after will default to **mcr.microsoft.com/businesscentral:ltsc2022**
This will ensure that people are always using the latest and fully updated (non-vulnerable) generic images.
=> use ltsc images

AppHandling/Compile-AppInNavContainer.ps1, AppHandling/Run-AlPipeline.ps1, CompilerFolderHandling/Compile-AppWithBcCompilerFolder.ps1, ReleaseNotes.txt
Allow CustomCodeCops to be a URL (instead of a file shared with the container)
f.ex. https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/download/v0.30.0/BusinessCentral.LinterCop.current.dll
Remember that some customCodeCops requires you to set vsixFile = latest as well.
=> Customcodecops

AzureAD/Remove-AadAppsForBc.ps1
Use SecureString for AccessToken in Remove-AadAppsForBc if necessary:
I added a check to use Convert the AccessToken to a SecureString if it's required for `Connect-MgGraph` .
and 
Fix #3472
=> Improvements for Remove-AadAppsForBc 

AppHandling/Publish-NavContainerApp.ps1, Common/Download-File.ps1, ContainerHandling/Get-NavContainerSession.ps1, ContainerInfo/Get-NavContainerArtifactUrl.ps1, ContainerInfo/Get-NavContainerCountry.ps1, ContainerInfo/Get-NavContainerDebugInfo.ps1, ContainerInfo/Get-NavContainerEula.ps1, ContainerInfo/Get-NavContainerEventLog.ps1, ContainerInfo/Get-NavContainerGenericTag.ps1, ContainerInfo/Get-NavContainerId.ps1, ContainerInfo/Get-NavContainerImageLabels.ps1, ContainerInfo/Get-NavContainerImageName.ps1, ContainerInfo/Get-NavContainerImageTags.ps1, ContainerInfo/Get-NavContainerIpAddress.ps1, ContainerInfo/Get-NavContainerLegal.ps1, ContainerInfo/Get-NavContainerLicenseInformation.ps1, ContainerInfo/Get-NavContainerName.ps1, ContainerInfo/Get-NavContainerNavVersion.ps1, ContainerInfo/Get-NavContainerOsVersion.ps1, ContainerInfo/Get-NavContainerPath.ps1, ContainerInfo/Get-NavContainerPlatformVersion.ps1, ContainerInfo/Get-NavContainerServerConfiguration.ps1, ContainerInfo/Get-NavContainerSharedFolders.ps1, ContainerInfo/Get-NavContainers.ps1, HelperFunctions.ps1
Session caching didn't really work in the latest preview
+ telemetry in the low level functions can be measured in perf.
=> session bug + remove telemetry from low level functions

ContainerInfo/Test-NavContainer.ps1
Using an empty string as parameter not works in pwsh.
**This code fails in PS7.x**
```powershell
$a = ""
docker ps $a
```
**This code works in PS5.x and PS7.x**
```powershell
$a = $null
docker ps $a
```
=> compatibility with pwsh

AzureAD/New-AadAppsForBc.ps1, ReleaseNotes.txt
This pull request enhances the `New-AadAppsForBc` PowerShell function by adding functionality to automatically grant admin consent to the permissions requested by the created app registration. This update ensures that applications created using this function will have the necessary permissions without requiring manual admin consent, streamlining the setup process. More details: #3206
**Changes:**
- Added code to automatically grant admin permissions to the created application registration if the `autoConsent` parameter is present.
=> Auto-Consent Functionality to New-AadAppsForBc added

NavContainerHelper.md
This pull request introduces a new section to the `NavContainerHelper.md` documentation, detailing how to set up Traefik for managing multiple Business Central Docker containers with SSL certificates. The new instructions cover both the use of Let's Encrypt and the use of custom SSL certificates with OpenSSL. #3210
**Changes:**
- Added a new section titled "Use Traefik for Multiple Business Central Containers".
- Included detailed steps for setting up Traefik with Let's Encrypt.
- Provided instructions for converting PFX files to CRT and KEY files using OpenSSL for custom SSL certificate setup.
- Added relevant PowerShell commands for configuring Traefik and creating Docker containers with Traefik.
=> Add Traefik Setup Instructions for Business Central Docker Containers

BC.HelperFunctions.ps1
int types are different coming from ConvertFrom-Json (int32 in PS5.1 and int64 in PS7)
=> Issue #3555

Misc/Set-BcContainerFeatureKeys.ps1
Mea Culpa - Despite the fact I confirmed it works correctly, A few days ago I provided wrong code from incorrect branch in my repository. Sorry for that. Never will happen again.
=> Correction - wrong error handling removed during SQL line insertion command

CompilerFolderHandling/New-BcCompilerFolder.ps1
I probably found a missing app handling in `New-BcCompilerFolder`. When populating the cache folder, "Business Foundation Test Libraries" is not being copied to the symbols folder. Therefore, apps that have a dependency on it will not compile due to missing symbols.
Example:
```
$artifactURL = "https://bcartifacts-exdbf9fwegejdqak.b02.azurefd.net/sandbox/25.0.23364.25278/de"
$compilerFolder = New-BcCompilerFolder -artifactUrl $artifactURL -includeAL
$symbolsFolder = Join-Path $compilerFolder "symbols"
$filePattern = "Microsoft_Business Foundation Test Libraries*.app"
$fileCheck = Get-ChildItem -Path $symbolsFolder -Filter $filePattern
if ($fileCheck) {
Write-Host "File exists in the folder: $symbolsFolder" # result with fix
} else {
Write-Host "File does NOT exist in the folder: …
```
=> Copy Business Foundation Test Libraries app to symbols folder in New-BcCompilerFolder

ReleaseNotes.txt, Saas/Publish-PerTenantExtensionApps.ps1
This PR should fix some instabilities when publishing many apps to an online service.
It fixes:
- A constant renewal of the authcontext when expired
- Some times the Nav.Upload API call resulted in an error in the server - but the app was still uploaded
Fixes #3628
=> Add resilience to publishing

CompilerFolderHandling/Compile-AppWithBcCompilerFolder.ps1
We've been seeing tons of errors like this in the latest preview version of containerhelper: 
https://github.com/microsoft/BCApps/actions/runs/11379580839/job/31657319047#step:8:1194
```
Error: Unexpected error when running action. Error Message: The property 'appid' cannot be found on this object. Verify that the property exists.,
```
As far as I can see it's because the addDependencies isn't initialized correctly
=> Fix init of addDependencies

AppHandling/Run-AlPipeline.ps1
`Run-AlPipeline` fails with message like:
```
Error: AL1033 An error occurred while loading the included rule set file c:\sources\..\..\..\src\rulesets\ruleset.json - Could not find a part of the path 'c:\src\rulesets\ruleset.json'.
```
E.g. https://github.com/microsoft/BCApps/actions/runs/11567038300/job/32196982417?pr=2272
=> Fix CheckRelativePath

NuGet/New-BcNuGetPackage.ps1, NuGet/NuGetFeedClass.ps1, ReleaseNotes.txt
We found that `Compress-Archive` and especially storing the `octet-stream` inside a string instead of using a Stream causes a very high memory consumption and a bad performance.
We're invoking the BcNuGet Cmdlets from our own C# API and therefore were able to profile the memory and performance. The behaviour however is similar when invoking the Cmdlets directly (PowerShell Core 7.4.6).
**Memory (Note: around 340 MB is the base load our API brings with it)**
Before: Memory spikes when uploading big apps, around 1 GB memory consumption from BcNuGet Cmdlets
After: 
**Performance**
Before:
After:
=> [BcNuGet] Reduce memory consumption, improve performance, prevent memory leaks

BC.HelperFunctions.ps1, Bacpac/Restore-BcDatabaseFromArtifacts.ps1, ContainerHandling/New-NavContainer.ps1, ReleaseNotes.txt
Fixes #3762 
This is a change to how Restore-BcDatabaseFromArtifacts chooses which PowerShell module to use. I have added an optional parameter, SqlModuleToUse, with two possible values, sqlps and sqlserver, and a default value of sqlps to preserve existing functionality.
I've also added the same parameter to New-BcContainer.
=> Give Option to Choose SQL PowerShell Module When Restoring From BacPac

NuGet/Download-BcNuGetPackageToFolder.ps1, NuGet/Publish-BcNuGetPackageToContainer.ps1, ReleaseNotes.txt
For runtime creation / OnPrem deployments it's usually needed to retrieve runtime packages with the earliest matching version. This approach feels almost too easy so please point out if I missed something but it seemed to resolve the way I want it to.
#3590
=> EarliestMatching search for Download-BcNuGetPackageToFolder

CompilerFolderHandling/Compile-AppWithBcCompilerFolder.ps1
We have the problem, that we have a app which is named "System" as well. The problem is that we get the following error when we use the funciton `Compile-AppWithBcCompilerFolder`: 
Therefore we need to also check the publisher of the dependency to avoid the error and wrong behaviour in the other places.
=> Extend condition to check for name and publisher

AppHandling/Compile-AppInNavContainer.ps1, AppHandling/Run-AlPipeline.ps1, NuGet/Download-BcNuGetPackageToFolder.ps1, NuGet/Publish-BcNuGetPackageToContainer.ps1, ReleaseNotes.txt
This PR is the BcContainerHelper part of making sure that the installed apps, the platform and the country are transferred to NuGet resolution when locating apps for downloading - making sure that you don't download a package with dependencies to BC which is newer than what you are building for.
It is a requirement for https://github.com/microsoft/AL-Go/pull/1450
=> CompilerFolder doesn't transfer installed Apps to NuGet resolution

AppSource/Invoke-IngestionAPI.ps1
Add retry logic for Ingestion API status codes:
- 503 - Service Unavailable
- 504 - Gateway Timeout
=> Add retry logic for Ingestion API 503 and 504 HTTP status codes.

AppHandling/Run-AlPipeline.ps1, ReleaseNotes.txt
During Run-AlPipeline, apps which are only published are reported as being installed, which leads to error 1530 in AL-Go repository
=> Apps, which only are published are included in installedapps

ReleaseNotes.txt
Use standard app filename for app instead of the app name inside the nuget package
=> release note

AppHandling/Run-AlPipeline.ps1
Run-AlPipeline will fail during InstallMissingDependencies if there are no apps installed. In [BCApps](https://github.com/microsoft/BCApps) we uninstall all apps during NewBCContainer since we need to publish and install a new System App, Business Foundation etc. 
```
Error: Unexpected error when running action. Error Message: The property 'Id' cannot be found on this object. Verify that the 
property exists., StackTrace: at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.1.4-
preview1309\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 1467 <- at <ScriptBlock>, 
C:\ProgramData\BcContainerHelper\6.1.4-preview1309\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 1467 <- at 
<ScriptBlock>, C:\ProgramData\BcContainerHelper\6.1.4-preview1309\BcContainerHelper\AppHandling\Run-AlPi …
```
=> Handle empty installedApps during InstallMissingDependencies

Artifacts/Download-Artifacts.ps1, Bacpac/Restore-BcDatabaseFromArtifacts.ps1, CompilerFolderHandling/New-BcCompilerFolder.ps1, ContainerHandling/New-NavContainer.ps1, ContainerHandling/New-NavImage.ps1
Add support for the new dvd folder layout in version 27 due to the change to Wix 6 msi builder. The dvd folders now uses tokenized names and not the real Windows names (like pfiles64 and not "Program Files"),
=> Update dvd paths to handle new folder layout with Wix 6 msi builder.

BC.HelperFunctions.ps1, NuGet/Download-BcNuGetPackageToFolder.ps1, NuGet/NuGetFeedClass.ps1
GitHub Packages stopped working after https://github.com/microsoft/navcontainerhelper/pull/3901
GitHub Packages nuget endpoint doesn't support directly downloading the nuspec file - instead we have to download package information elsewise
=> GitHub Packages stopped working

AppHandling/Run-AlPipeline.ps1, BC.HelperFunctions.ps1, ReleaseNotes.txt
If compilefolders are used the packages folder will be deleted and recreated during the pipeline run.
In certain cases especially when you use customized AL:Go with foreign container systems, this folder exists on purpose and already includes files. This files should not be deleted because it will lead the pipeline to fail
=> Don't remove packagesFolder if it already exists

NuGet/Get-BcNuGetPackageId.ps1, ReleaseNotes.txt
If a publisher name or app name consists of only UTF8 characters, we would issue an error.
If a package id ended up having a minus in front of a period (-.), nuGet would fail on publishing.
=> NuGet naming fixes

AppHandling/Sort-AppFoldersByDependencies.ps1, ReleaseNotes.txt
Give a better error in a situation like https://github.com/microsoft/AL-Go/issues/1695
=> fail early if app.json isn't valid

ContainerHandling/New-NavContainer.ps1
Remove .NET 6 assemblies in BC 27 and higher
=> Remove .NET 6 assemblies in BC 27 and higher

.github/workflows/CI.yaml, .github/workflows/Release.yaml
When releasing bccontainerhelper we upload the new version to a storage account. When these blobs are accessed through AFD we should specify what the cache duration should be so AFD takes that into consideration.
=> Add cache control during releases

.github/workflows/StaleIssues.yaml
Utilize https://github.com/actions/stale/
=> Add workflow to mark stale issues

Tests/AppHandling (NAV).Tests.ps1, Tests/Bacpac (MT).Tests.ps1, Tests/Bacpac (NAV).Tests.ps1, Tests/GetAndRunTests (version 10).Tests.ps1, Tests/GetAndRunTests (version 11).Tests.ps1, Tests/GetAndRunTests (version 14).Tests.ps1, Tests/GetAndRunTests (version 9).Tests.ps1, Tests/ObjectHandling (NAV).Tests.ps1, Tests/TenantHandling.Tests.ps1
The skipped tests are failing due to the error on missing ODBC driver (needed to support .fob files import for older NAV versions)
Test run: https://github.com/microsoft/navcontainerhelper/actions/runs/16145608366
=> Disable failing tests due to the error on missing ODBC driver of older NAV versions

Artifacts/Download-Artifacts.ps1
If a manifest ends up in a corrupt state or is deleted without the rest of the artifact being deleted, you may run into the following error:
`Error Message: The variable '$appManifest' cannot be retrieved because it has not been set.`
This PR adds some defensive checks to ensure that the file both exists and is not corrupt. If it is, the artifact is redownloaded to ensure that we have a valid manifest file.
Fixes #3981
=> Better handling for missing or corrupt manifest files

AppHandling/Extract-AppFileToFolder.ps1, AppHandling/Run-AlPipeline.ps1
With the introduction of Ready-2-Run apps the format of the .app files has been slightly changed. Before, the content of an app file looked like this: 
Now it looks like this:
Where the embedded app file is the "real" app file. 
To handle this, I'm adding a recursive call to Extract-AppFileToFolder in case it is a ready-2-run app. 
Related to #4001
=> Update Extract-AppFileToFolder to handle Ready-2-Run apps 

ContainerHandling/Flush-ContainerHelperCache.ps1
Small fix to a comparison in Flush-ContainerHelperCache where a non-lower string is compared to the input cache, but the input cache is forced to always be lower letters.
=> Fix: non small/lower letters used in Flush-ContainerHelperCache comparison.

AppHandling/Clean-BcContainerDatabase.ps1, AppHandling/Compile-AppInNavContainer.ps1, ReleaseNotes.txt
With v27 the applicationVersion is gone from the $ndo$dbproperty table. There are a couple of places in BCContainerHelper where we try to fetch the application version from this property. We'll need to update that.
Related to: #4018
=> Stop trying to fetch applicationversion from v27+ databases 
